### ISSUE TITLE
[FeatureRequest] 同値のPrefab OverrideのRevert機能

### ISSUE THREAD

**Issue by Tliks** [nekobako/EditorPatcher#2]
Prefab内のプロパティは一回触ると同値に戻してもオーバーライドになるUnityの仕様を変更するような動作の機能が欲しいです。
一時的に触ったBlendShapeなどにも該当するため、既存のSkinned Mesh Renderer Editorとも関係する要素かと思います。

なお、[このような実装](https://github.com/Tliks/com.aoyon.fix-override/tree/15336e428354e71c462073ab6b142511968ac567/Editor)(同値のOverrideを自動でRevert)で構わなければPRを送れます。Editorの動作変更に近いのと、Skinned Mesh Renderer Editorと関連するためこちらに含めた方が良いのでは考えた次第です。

https://github.com/user-attachments/assets/6c254e01-48ba-4260-9c93-a36c6c52226d

EditorPatcherに含める機能でないという場合はクローズしてもらって構いません。

**Comment by nekobako** [comment]
ありがとうございます。便利そうですね…！
PR 送っていただけたら取り込めます。

`ObjectChangeEventStream` が 2021.3 からのようなので、それ以前の環境では非対応ということでエラーにならないようにだけしておいていただけると助かります。
